In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [6]:
# print the names of the four features
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
# print integers representing the species of each observation
print iris.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
# print the encoding scheme for species : 0 = setosa, 1 = versicolor, 2 = virginica
print iris.target_names

['setosa' 'versicolor' 'virginica']


In [9]:
# check the types of the features and response
print type(iris.data)
print type(iris.target)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [10]:
# check the shape of the features (first dimension = number of observations, second dimensions = number of features)
print iris.data.shape

(150L, 4L)


In [11]:
# check the shape of the response (single dimension matching the number of observations)
print iris.target.shape

(150L,)


In [12]:
# store feature matrix in "X"
X = iris.data

# store response vector in "Y"
Y = iris.target

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn = KNeighborsClassifier(n_neighbors=1)

In [17]:
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')


In [18]:
knn.fit(X,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [19]:
X = iris.data

In [20]:
from sklearn.datasets import load_iris

In [22]:
iris = load_iris()

In [23]:
y=iris.target

In [24]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [25]:
knn.predict([3,5,4,2])

array([2])

In [26]:
knn.predict([1,2,3,4])

array([2])

In [27]:
knn.predict([6,8,10,1])

array([2])

In [28]:
X_new=([3,5,4,2],[5,4,3,2])
knn.predict(X_new)

array([2, 1])

In [29]:
knn=KNeighborsClassifier(n_neighbors=5)

In [30]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=5, p=2, weights='uniform')

In [31]:
knn.predict(X_new)

array([1, 1])

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg = LogisticRegression()

In [34]:
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [35]:
logreg.predict(X_new)

array([2, 0])

In [36]:
logreg.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
y_pred = logreg.predict(X)

In [38]:
len(y_pred)

150

In [39]:
from sklearn import metrics
print metrics.accuracy_score(y, y_pred)

0.96


In [40]:
print X.shape
print y.shape

(150L, 4L)
(150L,)


In [41]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=0.4, random_state=4)

In [42]:
print X_train.shape
print X_test.shape

(90L, 4L)
(60L, 4L)


In [43]:
print y_train.shape
print y_test.shape

(90L,)
(60L,)


In [44]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [45]:
y_pred = logreg.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

0.95


In [46]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

0.966666666667


In [47]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred)

0.95


In [49]:
k_range = range(1, 26)